# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 689ab47c0ab885369584a958f9f8995fc3c51c705c3b784d722e6fb4e9393a85cc2ee6108f96d6957ab2ff3e571741c119794ee3278ec17f18ffb473723d85f8

test:
  secret_key_base: 6ae92c79fd1b2450a8667be24b6baf5d5794ac760b9e8f03c87460d99b8c5c20787b6f18ec1fa7f994e0708b5fe71caf53d59048368f48c1c54cd52e58dd81fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
